# NumPy Arrays 

## Exercise 3.01: Creating a NumPy Array (from a List)

In [1]:
# import NumPy
import numpy as np

# create a list with three elements
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [2]:
# use the array function to convert it to an array
array_1 = np.array(list_1)
array_1

array([1, 2, 3])

In [3]:
# create an array of floating type elements
a = np.array([1.2, 3.4, 5.6])
a

array([1.2, 3.4, 5.6])

In [4]:
# check the type of the newly created object
type(a)

numpy.ndarray

In [5]:
# use the type function to check the type
type(array_1)

numpy.ndarray

In [6]:
# use the type function on list_1
type(list_1)

list

In [8]:
# read a .csv file as a NumPy array using the genfromtxt function built-in to NumPy
data = np.genfromtxt('./datasets/stock.csv', \
                    delimiter=',',names=True,dtype=None, \
                    encoding='ascii')
data

array([('MMM', 100), ('AOS', 101), ('ABT', 102), ('ABBV', 103),
       ('ACN', 104), ('ATVI', 105), ('AYI', 106), ('ADBE', 107),
       ('AAP', 108), ('AMD', 109), ('AES', 110), ('AET', 111),
       ('AMG', 112), ('AFL', 113), ('A', 114), ('APD', 115),
       ('AKAM', 116), ('ALK', 117), ('ALB', 118), ('ARE', 119),
       ('ALXN', 120), ('ALGN', 121), ('ALLE', 122), ('AGN', 123),
       ('ADS', 124), ('LNT', 125), ('ALL', 126), ('GOOGL', 127),
       ('GOOG', 128), ('MO', 129), ('AMZN', 130), ('AEE', 131),
       ('AAL', 132), ('AEP', 133), ('AXP', 134), ('AIG', 135),
       ('AMT', 136), ('AWK', 137), ('AMP', 138), ('ABC', 139),
       ('AME', 140), ('AMGN', 141), ('APH', 142), ('APC', 143),
       ('ADI', 144), ('ANDV', 145), ('ANSS', 146), ('ANTM', 147),
       ('AON', 148)], dtype=[('Symbol', '<U5'), ('Price', '<i4')])

In [9]:
# use the type function to check data
type(data)

numpy.ndarray

## Exercise 3.02: Adding Two NumPy Arrays

In [10]:
# declare a Python list
list_1 = [1,2,3]
# create an array from list_1
array_1 = np.array(list_1)

In [11]:
# use the `+` to concatenate two list_1 objects and save to a new variable
list_2 = list_1 + list_1
list_2

[1, 2, 3, 1, 2, 3]

In [12]:
# use the `+` to concatenate two array_1 objects and save to a new variable
array_2 = array_1 + array_1
array_2

array([2, 4, 6])

In [15]:
# load a .csv file and concatenate it with itself
data = np.genfromtxt('./datasets/numbers.csv', \
                    delimiter=',', names=True)
data = data.astype('float64')
data + data

array([202., 204., 206., 208., 210., 212., 214., 216., 218., 220., 222.,
       224., 226., 228., 230., 232., 234., 236., 238., 240., 242., 244.,
       246., 248., 250., 252., 254., 256., 258., 260., 262., 264., 266.,
       268., 270., 272., 274., 276., 278., 280., 282., 284., 286., 288.,
       290., 292., 294., 296.])

## Exercise 3.03: Mathematical Operations on NumPy Arrays

In [17]:
# create a NumPy array from the .csv file
data = np.genfromtxt('./datasets/numbers.csv', \
                    delimiter=',', names=True)
data = data.astype('float64')
data

array([101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
       123., 124., 125., 126., 127., 128., 129., 130., 131., 132., 133.,
       134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
       145., 146., 147., 148.])

In [18]:
# multiply 45 by every element in the array
data * 45

array([4545., 4590., 4635., 4680., 4725., 4770., 4815., 4860., 4905.,
       4950., 4995., 5040., 5085., 5130., 5175., 5220., 5265., 5310.,
       5355., 5400., 5445., 5490., 5535., 5580., 5625., 5670., 5715.,
       5760., 5805., 5850., 5895., 5940., 5985., 6030., 6075., 6120.,
       6165., 6210., 6255., 6300., 6345., 6390., 6435., 6480., 6525.,
       6570., 6615., 6660.])

In [19]:
# divide the array by 67.7
data / 67.7

array([1.49187592, 1.50664697, 1.52141802, 1.53618907, 1.55096012,
       1.56573117, 1.58050222, 1.59527326, 1.61004431, 1.62481536,
       1.63958641, 1.65435746, 1.66912851, 1.68389956, 1.69867061,
       1.71344165, 1.7282127 , 1.74298375, 1.7577548 , 1.77252585,
       1.7872969 , 1.80206795, 1.816839  , 1.83161004, 1.84638109,
       1.86115214, 1.87592319, 1.89069424, 1.90546529, 1.92023634,
       1.93500739, 1.94977843, 1.96454948, 1.97932053, 1.99409158,
       2.00886263, 2.02363368, 2.03840473, 2.05317578, 2.06794682,
       2.08271787, 2.09748892, 2.11225997, 2.12703102, 2.14180207,
       2.15657312, 2.17134417, 2.18611521])

In [20]:
# raise one array to the second array's power
list_1 = [1,2,3]
array_1 = np.array(list_1)
print("array_1 raised to the power of array_1: ", \
     array_1**array_1)

array_1 raised to the power of array_1:  [ 1  4 27]
