# NumPy Arrays 

## Exercise 3.01: Creating a NumPy Array (from a List)

In [1]:
# import NumPy
import numpy as np

# create a list with three elements
list_1 = [1,2,3]
list_1

[1, 2, 3]

In [2]:
# use the array function to convert it to an array
array_1 = np.array(list_1)
array_1

array([1, 2, 3])

In [3]:
# create an array of floating type elements
a = np.array([1.2, 3.4, 5.6])
a

array([1.2, 3.4, 5.6])

In [4]:
# check the type of the newly created object
type(a)

numpy.ndarray

In [5]:
# use the type function to check the type
type(array_1)

numpy.ndarray

In [6]:
# use the type function on list_1
type(list_1)

list

In [8]:
# read a .csv file as a NumPy array using the genfromtxt function built-in to NumPy
data = np.genfromtxt('./datasets/stock.csv', \
                    delimiter=',',names=True,dtype=None, \
                    encoding='ascii')
data

array([('MMM', 100), ('AOS', 101), ('ABT', 102), ('ABBV', 103),
       ('ACN', 104), ('ATVI', 105), ('AYI', 106), ('ADBE', 107),
       ('AAP', 108), ('AMD', 109), ('AES', 110), ('AET', 111),
       ('AMG', 112), ('AFL', 113), ('A', 114), ('APD', 115),
       ('AKAM', 116), ('ALK', 117), ('ALB', 118), ('ARE', 119),
       ('ALXN', 120), ('ALGN', 121), ('ALLE', 122), ('AGN', 123),
       ('ADS', 124), ('LNT', 125), ('ALL', 126), ('GOOGL', 127),
       ('GOOG', 128), ('MO', 129), ('AMZN', 130), ('AEE', 131),
       ('AAL', 132), ('AEP', 133), ('AXP', 134), ('AIG', 135),
       ('AMT', 136), ('AWK', 137), ('AMP', 138), ('ABC', 139),
       ('AME', 140), ('AMGN', 141), ('APH', 142), ('APC', 143),
       ('ADI', 144), ('ANDV', 145), ('ANSS', 146), ('ANTM', 147),
       ('AON', 148)], dtype=[('Symbol', '<U5'), ('Price', '<i4')])

In [9]:
# use the type function to check data
type(data)

numpy.ndarray

## Exercise 3.02: Adding Two NumPy Arrays

In [10]:
# declare a Python list
list_1 = [1,2,3]
# create an array from list_1
array_1 = np.array(list_1)

In [11]:
# use the `+` to concatenate two list_1 objects and save to a new variable
list_2 = list_1 + list_1
list_2

[1, 2, 3, 1, 2, 3]

In [12]:
# use the `+` to concatenate two array_1 objects and save to a new variable
array_2 = array_1 + array_1
array_2

array([2, 4, 6])

In [15]:
# load a .csv file and concatenate it with itself
data = np.genfromtxt('./datasets/numbers.csv', \
                    delimiter=',', names=True)
data = data.astype('float64')
data + data

array([202., 204., 206., 208., 210., 212., 214., 216., 218., 220., 222.,
       224., 226., 228., 230., 232., 234., 236., 238., 240., 242., 244.,
       246., 248., 250., 252., 254., 256., 258., 260., 262., 264., 266.,
       268., 270., 272., 274., 276., 278., 280., 282., 284., 286., 288.,
       290., 292., 294., 296.])

## Exercise 3.03: Mathematical Operations on NumPy Arrays

In [17]:
# create a NumPy array from the .csv file
data = np.genfromtxt('./datasets/numbers.csv', \
                    delimiter=',', names=True)
data = data.astype('float64')
data

array([101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
       123., 124., 125., 126., 127., 128., 129., 130., 131., 132., 133.,
       134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
       145., 146., 147., 148.])

In [18]:
# multiply 45 by every element in the array
data * 45

array([4545., 4590., 4635., 4680., 4725., 4770., 4815., 4860., 4905.,
       4950., 4995., 5040., 5085., 5130., 5175., 5220., 5265., 5310.,
       5355., 5400., 5445., 5490., 5535., 5580., 5625., 5670., 5715.,
       5760., 5805., 5850., 5895., 5940., 5985., 6030., 6075., 6120.,
       6165., 6210., 6255., 6300., 6345., 6390., 6435., 6480., 6525.,
       6570., 6615., 6660.])

In [19]:
# divide the array by 67.7
data / 67.7

array([1.49187592, 1.50664697, 1.52141802, 1.53618907, 1.55096012,
       1.56573117, 1.58050222, 1.59527326, 1.61004431, 1.62481536,
       1.63958641, 1.65435746, 1.66912851, 1.68389956, 1.69867061,
       1.71344165, 1.7282127 , 1.74298375, 1.7577548 , 1.77252585,
       1.7872969 , 1.80206795, 1.816839  , 1.83161004, 1.84638109,
       1.86115214, 1.87592319, 1.89069424, 1.90546529, 1.92023634,
       1.93500739, 1.94977843, 1.96454948, 1.97932053, 1.99409158,
       2.00886263, 2.02363368, 2.03840473, 2.05317578, 2.06794682,
       2.08271787, 2.09748892, 2.11225997, 2.12703102, 2.14180207,
       2.15657312, 2.17134417, 2.18611521])

In [20]:
# raise one array to the second array's power
list_1 = [1,2,3]
array_1 = np.array(list_1)
print("array_1 raised to the power of array_1: ", \
     array_1**array_1)

array_1 raised to the power of array_1:  [ 1  4 27]


## Exercise 3.04: Advanced Mathematical Operations on NumPy Arrays

In [21]:
# import pandas
import pandas as pd
df = pd.read_csv("./datasets/numbers.csv")
list_5 = df.values.tolist()
list_5

[[101],
 [102],
 [103],
 [104],
 [105],
 [106],
 [107],
 [108],
 [109],
 [110],
 [111],
 [112],
 [113],
 [114],
 [115],
 [116],
 [117],
 [118],
 [119],
 [120],
 [121],
 [122],
 [123],
 [124],
 [125],
 [126],
 [127],
 [128],
 [129],
 [130],
 [131],
 [132],
 [133],
 [134],
 [135],
 [136],
 [137],
 [138],
 [139],
 [140],
 [141],
 [142],
 [143],
 [144],
 [145],
 [146],
 [147],
 [148]]

In [22]:
# convert the list into a NumPy array
array_5 = np.array(list_5)
array_5

array([[101],
       [102],
       [103],
       [104],
       [105],
       [106],
       [107],
       [108],
       [109],
       [110],
       [111],
       [112],
       [113],
       [114],
       [115],
       [116],
       [117],
       [118],
       [119],
       [120],
       [121],
       [122],
       [123],
       [124],
       [125],
       [126],
       [127],
       [128],
       [129],
       [130],
       [131],
       [132],
       [133],
       [134],
       [135],
       [136],
       [137],
       [138],
       [139],
       [140],
       [141],
       [142],
       [143],
       [144],
       [145],
       [146],
       [147],
       [148]])

In [23]:
# sine function
np.sin(array_5)

array([[ 0.45202579],
       [ 0.99482679],
       [ 0.62298863],
       [-0.3216224 ],
       [-0.97053528],
       [-0.7271425 ],
       [ 0.18478174],
       [ 0.92681851],
       [ 0.81674261],
       [-0.04424268],
       [-0.86455145],
       [-0.8899956 ],
       [-0.09718191],
       [ 0.78498039],
       [ 0.94543533],
       [ 0.23666139],
       [-0.68969794],
       [-0.98195217],
       [-0.3714041 ],
       [ 0.58061118],
       [ 0.99881522],
       [ 0.49871315],
       [-0.45990349],
       [-0.99568699],
       [-0.61604046],
       [ 0.32999083],
       [ 0.97263007],
       [ 0.72103771],
       [-0.19347339],
       [-0.93010595],
       [-0.81160339],
       [ 0.05308359],
       [ 0.86896576],
       [ 0.88592482],
       [ 0.08836869],
       [-0.79043321],
       [-0.94251445],
       [-0.22805226],
       [ 0.69608013],
       [ 0.98023966],
       [ 0.36317137],
       [-0.58779501],
       [-0.99834536],
       [-0.49102159],
       [ 0.46774516],
       [ 0

In [24]:
# find the logarithmic value of the array
np.log(array_5)

array([[4.61512052],
       [4.62497281],
       [4.63472899],
       [4.6443909 ],
       [4.65396035],
       [4.66343909],
       [4.67282883],
       [4.68213123],
       [4.69134788],
       [4.70048037],
       [4.7095302 ],
       [4.71849887],
       [4.72738782],
       [4.73619845],
       [4.74493213],
       [4.75359019],
       [4.76217393],
       [4.77068462],
       [4.77912349],
       [4.78749174],
       [4.79579055],
       [4.80402104],
       [4.81218436],
       [4.82028157],
       [4.82831374],
       [4.83628191],
       [4.84418709],
       [4.85203026],
       [4.8598124 ],
       [4.86753445],
       [4.87519732],
       [4.88280192],
       [4.89034913],
       [4.8978398 ],
       [4.90527478],
       [4.91265489],
       [4.91998093],
       [4.92725369],
       [4.93447393],
       [4.94164242],
       [4.94875989],
       [4.95582706],
       [4.96284463],
       [4.9698133 ],
       [4.97673374],
       [4.98360662],
       [4.99043259],
       [4.997

## Exercise 3.05: Generating Arrays Using arange and linspace Methods

In [25]:
# create a series of numbers using arange
np.arange(5, 16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
# print numbers using the arange function
print("Numbers spaced apart by 2: ", \
     np.arange(0,11,2))
print("Numbers spaced apart by a floating point number: ",\
     np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order\n",\
     np.arange(30,-1,-5))

Numbers spaced apart by 2:  [ 0  2  4  6  8 10]
Numbers spaced apart by a floating point number:  [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order
 [30 25 20 15 10  5  0]


In [28]:
# use the linspace method for linearly spaced numbers
print("11 linearly spaced numbers between 1 and 5: ", \
     np.linspace(1,5,11))

11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


## Exercise 3.06: Creating Multi-Dimensional Arrays

In [29]:
# load the numbers2.csv 
# convert it to a two-dimensional NumPy array
df = pd.read_csv("./datasets/numbers2.csv",\
                header=None)
list_2D = df.values
mat1 = np.array(list_2D)
print("Type/Class of this object:",\
     type(mat1))
print("Here is the matrix\n----------\n", \
     mat1, "\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [30]:
# tupels can be converted into multi-dimensional arrays
tuple_2D = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(tuple_2D)
print(mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


## Exercise 3.07: The Dimension, Shape, Size and Data Type of Two-dimensional Arrays

In [31]:
# print the dimension of the matrix using the ndim function
print("Dimension of this matrix: ", mat1.ndim,sep='')

Dimension of this matrix: 2


In [32]:
# print the size of the matrix
print("Size of this matrix: ", mat1.size,sep='')

Size of this matrix: 9


In [33]:
# print the shape of the matrix
print("Shape of this matrix: ", mat1.shape,sep='')

Shape of this matrix: (3, 3)


In [34]:
# print the dimension 
print("Data type of this matrix: ", mat1.dtype,sep='')

Data type of this matrix: int64


## Exercise 3.08: Zeros, Ones, Random, Identity Matrices, and Vectors

In [35]:
# print the vector of zeros
print("Vector of zeros: ", np.zeros(5))

Vector of zeros:  [0. 0. 0. 0. 0.]


In [37]:
# print the matrix of zeros 
print("Matrix of zeros: ", np.zeros((3,4)))

Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
# print the matrix of fives
print("Matrix of 5's: ", 5*np.ones((3,3)))

Matrix of 5's:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [39]:
# print an identity matrix
print("Identity matrix of dimension 2: ", np.eye(2))

Identity matrix of dimension 2:  [[1. 0.]
 [0. 1.]]


In [40]:
# print an identity matrix with a dimension of 4x4
print("Identity matrix of dimension 4: ", np.eye(4))

Identity matrix of dimension 4:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
# print a matrix of random shape 
print("Random matrix shape(4,3):\n", \
     np.random.randint(low=1,high=10,size=(4,3)))

Random matrix shape(4,3):
 [[1 4 9]
 [9 7 7]
 [1 1 1]
 [6 2 2]]
